name: Node CI

on: [push]

jobs:
  test:
    name: Test on node 12 and ubuntu-latest
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        version: 12
    
    - name: npm install, build and test
      run: |
        npm install
        npm run build --if-present
        npm test
